import {
  ACTIVE_CONTENT_VALIDATION,
  AUTHORED_VERTICAL_SLICE_CONTENT_VALIDATION,
  AUTHORED_VERTICAL_SLICE_WORLD_VALIDATION,
  BALANCED_VERTICAL_SLICE_CONTENT_VALIDATION,
} from '../src/content/runtime-content-validation'

console.log(
  JSON.stringify(
    {
      active: ACTIVE_CONTENT_VALIDATION,
      verticalSlice: AUTHORED_VERTICAL_SLICE_CONTENT_VALIDATION,
      verticalSliceWorld: AUTHORED_VERTICAL_SLICE_WORLD_VALIDATION,
      verticalSliceBalanced: BALANCED_VERTICAL_SLICE_CONTENT_VALIDATION,
    },
    null,
    2,
  ),
)
